### ISSUE TITLE
new release

### ISSUE THREAD

**Issue by oberon-manjaro** [fontmatrix/fontmatrix#13]
Could you kindly do a new git release, please? It makes no sense, that AUR users who install the 'stable' package don't have the icu fix included...
Thank you.

**Comment by prokoudine** [comment]
The ICU fix is not the only thing that happened after the v0.6.0 release. The code is unstable as hell and unmaintained.

**Comment by RJVB** [comment]
Is there a more modern equivalent?

**Comment by prokoudine** [comment]
I have no foggiest idea what counts for "modern", but there is e.g. https://fontmanager.github.io/.

**Comment by RJVB** [comment]
The concept *more* modern is usually easier to define ;)

What I should have mentioned is that to me equivalent includes Qt-based and the the cross-platform nature that provides...

**Comment by prokoudine** [comment]
There you go: https://github.com/fontmatrix/fontmatrix/releases/tag/v0.9.100
