### ISSUE TITLE
Plans for Ubuntu 18.04

### ISSUE THREAD

**Issue by rsd** [fontmatrix/fontmatrix#14]
It seems that ICU and PythonQT in Ubutnu 18.04 are incompatible with fontmatrix.

**Comment by andrewjbennett** [comment]
I managed to get it working in Ubuntu 18.04 based on the steps on this page: https://community.linuxmint.com/tutorial/view/2414

(tldr: manually install the trusty (14.04) versions of libicu52, libm17n-0, then fontmatrix. I didn't have any issues installing the dependencies for the packages above)

**Comment by rsd** [comment]
that's trusty

**Comment by andrewjbennett** [comment]
Yes, I know.

I was able to install it on 18.04 by manually installing those trusty .debs
(after installing their prereqs via apt first).

**Comment by alexmyczko** [comment]
Guess you want this fork https://github.com/fcoiffie/fontmatrix

**Comment by calandoa** [comment]
The fork did not work on my 18.04.03.

The problems I found is that FindICU.cmake is broken, the official one is broken too, and you to force python 2.7:


`diff --git a/CMakeLists.txt b/CMakeLists.txt
index fee847b..0e16440 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -156,7 +156,7 @@ ENDIF(FREETYPE_FOUND)
 #>> FreeType2
 
 IF(WANT_PYTHONQT)
-       FIND_PACKAGE(PythonLibs REQUIRED)
+       FIND_PACKAGE(PythonLibs 2.7 REQUIRED)
        if(PYTHONLIBS_FOUND)
                MESSAGE(STATUS "Python Library Found OK")
        else(PYTHONLIBS_FOUND)
diff --git a/cmake/modules/FindICU.cmake b/cmake/modules/FindICU.cmake
index 5b1b1ba..5637e50 100644
--- a/cmake/modules/FindICU.cmake
+++ b/cmake/modules/FindICU.cmake
@@ -20,6 +20,7 @@
 FIND_PATH(
 ICU_INCLUDE_DIR 
 NAMES layout/LayoutEngine.h
+HINTS /usr/include/icu-le-hb
 DOC "Include directory for the ICU Layout library"
 )
 mark_as_advanced(ICU_INCLUDE_DIR)
@@ -28,7 +29,7 @@ mark_as_advanced(ICU_INCLUDE_DIR)
 # Look for the library.
 find_library(
   ICU_LIBRARY
-  NAMES icule cygicule cygicule32
+  NAMES icule cygicule cygicule32 icu-le-hb
   DOC "Libraries to link against for the common parts of ICU")
 mark_as_advanced(ICU_LIBRARY)
`

**Comment by alexmyczko** [comment]
build for me: http://sid.ethz.ch/debian/fontmatrix/qt5-3/

**Comment by alexmyczko** [comment]
I guess since fontmatrix is updated and officially in 20.04 and debian 11, this issue can be closed?
