### ISSUE TITLE
location of fontmatrix repository / dependencies

### ISSUE THREAD

**Issue by jeffmcneill** [fontmatrix/fontmatrix#15]
On this install instructions for Debian/Ubuntu:

https://github.com/fontmatrix/fontmatrix/blob/master/debian-ubuntu-install.txt

It says:

> then we install the various build dependencies already known by the package database by typing:
> sudo apt-get build-dep fontmatrix

However, using Debian9/LMDE3 the standard repositories do not seem to have the fontmatrix package. Please advise as to which repositories to point to. My main problem is not having a proper QT environment, according to the cmake error.

**Comment by prokoudine** [comment]
Mhm, sorry for the late response. Somehow I'm not getting emails for new issues.

The build instruction definitely works for me on Ubuntu 20.04 LTS. Although, admittedly, it will fetch Qt4 dev packages which is the wrong thing to do now that Fontmatrix is ported to Qt5. Hopefully, Debian/Ubuntu will build the new version.

**Comment by alexmyczko** [comment]
https://repology.org/project/fontmatrix/versions did with the fork 0.9.99 (qt5)... thanks for the new 0.9.100 release!
