### ISSUE TITLE
Building with Qt5?

### ISSUE THREAD

**Issue by nick-s-b** [fontmatrix/fontmatrix#20]
Hi all,
Given that qt4 has been EOL for 4 years now and many Linux distros don't even offer qt4 packages, has anyone tried to compile Fontmatrix with qt5? Fontmatrix is the only program on my machine that still requires qt4 and it's a massive pain to update. Today I attempted to update qt4 but I've run into a bunch of issues since the toolchain is now unstable and things fail to build.

Anyway, I'm wondering what others are doing or is this program now abandonware too.
Thanks!

**Comment by progandy** [comment]
There is a fork that compiles with qt5. I don't know if everything works as expected. (If you prefer the 0.6.0 version you'll have to merge the QAction commit from the master branch)

https://github.com/fcoiffie/fontmatrix

**Comment by alexmyczko** [comment]
build for me: http://phd-sid.ethz.ch/debian/fontmatrix/qt5-3/

**Comment by aoloe** [comment]
@prokoudine  do you need help for mergin fcoiffe's work into this branch?

**Comment by prokoudine** [comment]
Merged the patches.
