### ISSUE TITLE
please add *.ttc (truetype font collection) support

### ISSUE THREAD

**Issue by alexmyczko** [fontmatrix/fontmatrix#23]
a patch is available here:

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=579314

btw otf also has a collection container file type
https://en.wikipedia.org/wiki/OpenType#OpenType_Collections

**Comment by prokoudine** [comment]
Merged, thanks :)

**Comment by prokoudine** [comment]
@alexmyczko By the way, i do believe that https://github.com/fontmatrix/fontmatrix/commit/6aa472bfdf98f469aba9cf0a43c2353e207cc255 fixes https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=623475 too :)
