### ISSUE TITLE
text overlaps

### ISSUE THREAD

**Issue by kemelzaidan** [fontmatrix/fontmatrix#24]
I'm using the last 0.6.0 version and the text overlaps as showm on the screenshot attached. Is it a bug?

![Captura de tela de 2020-02-25 23-41-09](https://user-images.githubusercontent.com/897436/75307069-8e264e80-5829-11ea-8043-d7866af35a9c.png).

**Comment by prokoudine** [comment]
Yeah, probably. But this version is pretty much unsupported. Sorry.

**Comment by kemelzaidan** [comment]
It was the the version available at Ubuntu 19.10 repositories at that time. Thanks any way
