### ISSUE TITLE
Link to flathub Flatpak

### ISSUE THREAD

**Issue by hfiguiere** [fontmatrix/fontmatrix#28]
I  have submitted Fontmatrix to Flathub

https://github.com/flathub/flathub/pull/1834

When it gets merged, it would be nice to link to it to offer the Flatpak option to install fontmatrix.

**Comment by hfiguiere** [comment]
It can now be installed from https://flathub.org/apps/details/com.github.fontmatrix.Fontmatrix

**Comment by prokoudine** [comment]
Mentioned in both release notes and README now, thank you :)
