### ISSUE TITLE
Installing error

### ISSUE THREAD

**Issue by GCamp6** [fontmatrix/fontmatrix#8]
I'm trying to install fontmatrix in Debian (LMDE to be precise) following the steps described in the .txt file. After typing:

`svn co http://svn.gna.org/svn/undertype/trunk/tools/typotek fontmatrix`

I get:

```
svn: E000111: Unable to connect to a repository at URL 'http://svn.gna.org/svn/undertype/trunk/tools/typotek'
svn: E000111: Error running context: Connection rejected
```
Any hint on how to procede?

**Comment by jspaces** [comment]
Substitute the svn command with:
git clone https://github.com/fontmatrix/fontmatrix.git
This will allow you to get the fontmatrix source code then you should be able to proceed.

**Comment by GCamp6** [comment]
Well, the debian-ubuntu-install.txt I found here in GitHub!

https://github.com/fontmatrix/fontmatrix/blob/master/debian-ubuntu-install.txt

Line 13:

> then we retrive the source code by typing:
  sudo apt-get install subversion 
svn co http://svn.gna.org/svn/undertype/trunk/tools/typotek fontmatrix

**Comment by prokoudine** [comment]
Fixed in master
