### ISSUE TITLE
Windows binary

### ISSUE THREAD

**Issue by sergeevabc** [fontmatrix/fontmatrix#9]
Dear @prokoudine,
Could you be so kind to generate ```.exe``` for the rest of us who are mere Windows users w/o compiler?

Edit: fortunately, installer ```fontmatrix-0.6.0-win32.exe``` is still available [here][1].

[1]: http://ec.ccm2.net/br.ccm.net/download/files/fontmatrix-0.6.0-win32.exe

**Comment by prokoudine** [comment]
I wouldn't be able to anyway.

**Comment by prokoudine** [comment]
Added the installer file to the 0.6.0 release, thanks for reporting :)
